name: feqh_book
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.3
  cupertino_icons: ^1.0.8
  flutter_pdfview: ^1.4.1+1
  get: ^4.7.2
  google_fonts: ^6.3.1
  lottie: ^3.3.1
  path_provider: ^2.1.5
  pdf: ^3.11.3
  permission_handler: ^12.0.1
  printing: ^5.14.2
  url_launcher: ^6.3.2
  change_app_package_name: ^1.5.0
  rename_app: ^1.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/pdfs/
    - assets/app_icon.png   # أيقونة التطبيق

# إعداد أيقونة التطبيق
flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/app_icon.png"
  min_sdk_android: 21
